import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        heading: ['Plus Jakarta Sans', 'Inter', 'system-ui', 'sans-serif'],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "code-sm": ["Inter"],
        "headline-md": ["Inter"],
        "title-lg": ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "code-sm": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
      },
      spacing: {
        "base": "4px",
        "xxl": "48px",
        "gutter": "24px",
        "container-max": "1280px",
        "sm": "8px",
        "lg": "24px",
        "xs": "4px",
        "xl": "32px",
        "md": "16px",
        "margin-mobile": "16px"
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
          container: "#1e293b",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
          container: "#5bb8fe",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Stitch Custom Colors
        "tertiary": "#270c00",
        "on-secondary-container": "#00476e",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#001d31",
        "on-primary-fixed-variant": "#3c475a",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#bcc7de",
        "outline-variant": "#c5c6cd",
        "tertiary-fixed": "#ffdbca",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#8590a6",
        "on-surface-variant": "#45474c",
        "secondary-fixed-dim": "#93ccff",
        "tertiary-fixed-dim": "#ffb68e",
        "surface-dim": "#d8dadc",
        "surface-container": "#eceef0",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed": "#111c2d",
        "inverse-on-surface": "#eff1f3",
        "surface-tint": "#545f73",
        "surface": "#f7f9fb",
        "on-background": "#191c1e",
        "tertiary-container": "#471c00",
        "primary-fixed": "#d8e3fb",
        "surface-container-low": "#f2f4f6",
        "on-error-container": "#93000a",
        "inverse-primary": "#bcc7de",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "error-container": "#ffdad6",
        "surface-bright": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-container": "#de722c",
        "outline": "#75777d",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#331200",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#cce5ff",
        "on-tertiary-fixed-variant": "#763300",
        "on-secondary-fixed-variant": "#004b73"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-down": {
          from: { opacity: "0", transform: "translateY(-20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "slide-up": "slide-up 0.5s ease-out forwards",
        "slide-down": "slide-down 0.5s ease-out forwards",
        "scale-in": "scale-in 0.3s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
